CREATE TABLE IF NOT EXISTS Genre (
id SERIAL PRIMARY KEY,
name VARCHAR(40) NOT NULL
);

CREATE TABLE IF NOT EXISTS Artist (
id SERIAL PRIMARY KEY,
name VARCHAR(40) NOT NULL
);

CREATE TABLE IF NOT EXISTS Artist_Genre (
Artist_id INTEGER NOT NULL REFERENCES Artist(id),
Genre_id INTEGER NOT NULL REFERENCES Genre(id)
);


CREATE TABLE IF NOT EXISTS Albom (
id SERIAL PRIMARY KEY,
name VARCHAR(40) NOT NULL,
year INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS Track (
id SERIAL PRIMARY KEY,
name VARCHAR(40) NOT NULL,
duration INTEGER NOT NULL,
albom_id INTEGER NOT NULL REFERENCES Albom(id)
);

CREATE TABLE IF NOT EXISTS Artist_Albom (
Artist_id INTEGER NOT NULL REFERENCES Artist(id),
Albom_id INTEGER NOT NULL REFERENCES Albom(id)
);

CREATE TABLE IF NOT EXISTS Complication (
id SERIAL PRIMARY KEY,
name VARCHAR(40) NOT NULL,
year INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS Compl_Track (
Complication_id INTEGER NOT NULL REFERENCES Complication(id),
Track_id INTEGER NOT NULL REFERENCES Track(id)
);


